### ISSUE TITLE
Error: pandoc version 1.12.3 or higher is required and was not found

### ISSUE THREAD

**Issue by rgaiacs** [sol-eng/docker-r-session#64]
I'm using this Docker Image in GitLab and my runner terminated with

```
Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
```

Can we include Pandoc in this Docker image?

My GitLab CI configuration file is

```
image: rstudio/r-session-complete:bionic

run:
  script:
    - Rscript -e 'rmarkdown::render("report.Rmd")'
  artifacts:
    paths:
      - report.html
```
